version: "3.8"
# services:
#     backend:
#       build: ./backend
#       restart: unless-stopped
#       ports: 5000:5000
#       networks:
#         - backend
#         - frontend

#     frontend:
#       build:
#       context: ./frontend

# networks:
services:
  frontend:
    build: ./frontend #might need to have ./m6practice added
    ports:
      - 80:80
    container_name: datacomfrontend
    networks:
      - main

  backend:
    build: ./backend
    ports:
      - 5001:5001
    container_name: datacombackend
    networks:
      - main

networks:
  main:
