# USE THIS COMPOSE FILE WITH THE default DOCKER CONTEXT, WHEN UPLOADING TO DOCKER DESKTOP ONLY
version: "3.8"

services:
  mongodb:
    image: mongo:5.0.2
    container_name: M6Mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - main

  frontend:
    image: m6practice_frontend
    container_name: M6Frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - main
    restart: unless-stopped

  backend:
    image: m6practice_backend
    container_name: M6Backend
    env_file: ./backend/.env
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    networks:
      - main
    restart: unless-stopped
    depends_on:
      - mongodb

networks:
  main:
